### ISSUE TITLE
Release a new version to crates.io

### ISSUE THREAD

**Issue by Nertsal** [geng-engine/geng#72]
There have not been new releases for a long time, but working with a git dependency is not very convenient, especially when building libraries that depend on the engine.

Here's a list of things that need to be done before the release:
- [ ] Fix or change [rodio](https://github.com/geng-engine/rodio/tree/mp3-duration) dependency
- [ ] Remove or update draw2d api

**Comment by kuviman** [comment]
idk why you wanted to do anything with draw2d, just published as is
